### ISSUE TITLE
.Now will be deprecated with Hugo v0.20

### ISSUE THREAD

**Issue by digitalcraftsman** [ExchangeRate-API/strange-case#2]
`.Now` will be deprecated replaced with the `now` template function in Hugo v0.20 which eventually will be released on Monday. It's likely that the deprecation will cause builds to fail.

**Comment by zx76** [comment]
Thanks so much for letting me know about this.

I can see how I should update it - but I can't see how I could make some kind of branch in the template for older versions which don't support `now` yet. I see the Ubuntu 16.04 package is still at 0.16.

I searched the docs but couldn't find any sort of template function that returns the version of Hugo the user is at?

**Comment by digitalcraftsman** [comment]
> I can see how I should update it - but I can't see how I could make some kind of branch in the template for older versions which don't support now yet. I see the Ubuntu 16.04 package is still at 0.16.

Such packages aren't maintained by us officially. So we (the maintainers of Hugo) don't have direct influence on the packages.

> I searched the docs but couldn't find any sort of template function that returns the version of Hugo the user is at?

In other words you want to keep your theme backwards compatible. I haven't thought about that :+1: 
Perhaps you can use the [`:Hugo.Version`](https://gohugo.io/templates/variables/#hugo-variables) variable to check whether the current version is smaller than v0.20.

**Comment by zx76** [comment]
Sorry for not closing this issue - I did update to `now` a while ago.
