### ISSUE TITLE
increasing the width of the displayed post

### ISSUE THREAD

**Issue by pfrcks** [ExchangeRate-API/strange-case#3]
Hi,

is there a way to increase the width of the displayed post?

**Comment by zx76** [comment]
Hi

Sorry for the slow reply.

I don't plan to add customizable post widths at this point. However, you could adjust this in your fork of the theme by changing the `col-sm-*`, `col-md-*`, `col-lg-*` sizes of the `content` class div in each of the files in the `layouts` & `layouts/_default` folders.

Just remember to change the column sizes in the placeholder div after the `content` class div to match up. You shouldn't need to change the `col-*-offset-*` values unless you're adjusting the size of the sidebar.
