### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [ExchangeRate-API/strange-case#7]
Hello!

I've stumbled upon the very same issue as the https://github.com/dim0627/hugo_theme_beg/issues/19, only part of the image visible on the screenshot where whole should be:

![image](https://user-images.githubusercontent.com/712534/37675688-f113afcc-2c86-11e8-9ec7-94d895aab932.png)

Source code:

    ![Shinken simple distributed architecture](https://shinken.readthedocs.io/en/latest/_images/shinken-architecture.png)

**Comment by zx76** [comment]
Hi @paskal 

Thanks for letting me know about this. See 52bd515e7a5aec4118239b6d7f1a92664e8c5127 for the fix.
