### ISSUE TITLE
Strange Case demo no longer genarates on the Hugo website

### ISSUE THREAD

**Issue by onedrawingperday** [ExchangeRate-API/strange-case#9]
Hello @bimmer44 

I am one of the maintainers of [Hugo Themes](https://github.com/gohugoio/hugoThemes)

The release of Hugo 0.53 had a bug fix for [case handling in cast params ](https://github.com/gohugoio/hugo/commit/64b6b290751df01c47ff8d8fe21a3eca7a5db283)

However due to this fix the theme demo no longer generates due to the following ERROR

```
Error building site: failed to render pages: render of "page" failed: "/opt/build/repo/strange-case/layouts/_default/single.html:16:80": execute of template failed: template: _default/single.html:16:80: executing "_default/single.html" at <.Site.Params.datefor...>: invalid value; expected string
```
To fix this ERROR you will need to provide an Example Site. ( Please see the [Artist theme's exampleSite](https://github.com/digitalcraftsman/hugo-artists-theme/tree/master/exampleSite) for a good example) or  if it's too much work for you (to create an Example Site from scratch) then simply clone the [Hugo Basic Example](https://github.com/gohugoio/hugoBasicExample/) and use it under the `/exampleSite/` directory.

Then in `exampleSite/config.toml` make sure to enter the following parameter:
```
[params]
dateformat = "Jan 2, 2006"
```
Simply entering the missing `dateformat` parameter fixes the ERROR and the demo will be once again generated.

Please do the above so that your theme's demo will be generated again. 

We recently had a spring cleaning of broken themes on the Themes website and it would be a shame if we had to remove this theme also.

Thank you.

ref: gohugoio/hugoThemes#531

**Comment by zx76** [comment]
Hi @onedrawingperday 

Thanks for alerting me to this and sorry for the slow response.

I've added an exampleSite directory and set the dateformat [params]. Please let me know if anything further is required.

**Comment by onedrawingperday** [comment]
Hello @bimmer44 

Thank you for looking into this. Now when I test your theme with the Hugo Site Build Script the demo generates. This will be reflected on the website the next time that the Themes are updated in the Hugo repository.
